folio-org/mod-circulation-storage

- ramls/loan-rules-storage.raml
It is used by traits/validation.raml
Fixes warning from raml-cop
> Add "errors" schema loan-rules-storage.raml folio-601

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/FixedDueDateSchedulesAPI.java
Includes changes to CQLQueryValidationException handling
as this is now included as the cause of a failure
rather than thrown as an exception
> Upgrade RAML Module Builder to 19.1.5 CIRCSTORE-62

- reference-data/loan-rules-storage/use-example-for-everything.json
Towards FOLIO-1334. Original loan rule referenced the format as `book`.
> Update reference loan rule to use UUID for format.

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/cancellation-reason.json
- ramls/examples/cancellation-reason.json
- ramls/examples/cancellation-reasons.json
- reference-data/cancellation-reason-storage/cancellation-reasons/needed-for-course-reserves.json
- src/test/java/org/folio/rest/api/CancellationReasonsApiTest.java
Handles [CIRCSTORE-66](https://issues.folio.org/browse/CIRCSTORE-66) which was necessitated by [UIREQ-99](https://issues.folio.org/browse/UIREQ-99).
> CIRCSTORE-66: Added publicDescription field to cancellation-reasons

- NEWS.md
- README.MD
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/loan-storage.raml
- src/main/java/org/folio/rest/impl/LoansAPI.java
- src/main/java/org/folio/support/ResultHandlerFactory.java
- src/main/java/org/folio/support/ServerError.java
- src/main/java/org/folio/support/ServerErrorResponder.java
- src/main/java/org/folio/support/UUIDValidation.java
- src/main/java/org/folio/support/VertxContextRunner.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/api/loans/LoansAnonymizationApiTest.java
- src/test/java/org/folio/rest/support/MultipleRecords.java
- src/test/java/org/folio/rest/support/http/AssertingRecordClient.java
- src/test/java/org/folio/rest/support/matchers/UUIDMatchers.java
- src/test/java/org/folio/support/ResultHandlerFactoryTest.java
- src/test/java/org/folio/support/ResultHandlerTest.java
- src/test/java/org/folio/support/ServerErrorResponderTest.java
- src/test/java/org/folio/support/VertxContextRunnerTest.java
*Purpose*
https://issues.folio.org/browse/CIRCSTORE-73
In order to anonymize all of the closed loans (and related action history) for a single user whilst reducing the quantity of HTTP requests to achieve this, we could introduce an endpoint that anonymizes a single users closed loans and loan action history in a single request.
*Approach*
* Chose to use SQL instead of fetching and updating all loans and then all related loan action history records, as two statements seemed simpler than nested asynchronous requests (see limitations below for improvements needed)
*Limitations*
The SQL is constructed with string concatenation, due to the `userId` being an external parameter this could potentially be used for injection (the validation below is an attempt to partly mitigate that). This should …
> Anonymize single users closed loans CIRCSTORE-73

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/examples/loan.json
- ramls/loan.json
Resolves [CIRCSTORE-77](https://issues.folio.org/browse/CIRCSTORE-77):
This adds the properties checkinServicePointId and checkoutServicePointId, both strings pattern matched to UUIDs, to the loan schema. This is a perquisite for [CIRC-104](https://issues.folio.org/browse/CIRC-104)
> Circstore 77

- descriptors/ModuleDescriptor-template.json
- ramls/examples/request-policies.json
- ramls/examples/request-policy.json
- ramls/request-policies.json
- ramls/request-policy-storage.raml
- ramls/request-policy.json
- ramls/request-policy.raml
- ramls/request-type.json
- src/main/java/org/folio/rest/impl/RequestPoliciesAPI.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
Added a new set of CRUD APIs for RequestPolicy at: /request-policy-storage/request-policies
- created new database table "request_policy" 
- added corresponding ramls and json schemas
- added request-type.json schema for request types, which can be reused elsewhere.
- the only business logic implemented is validation that request-policy name is required and unique
- implementation is based on previous CRUD implementations in the module
- all error messages are wrapped in the Error JSON structure. 
Cannot add tests to cover all the exception and negative cases because it's virtually impossible to trigger errors for them.
> Implement CRUD

- ramls/request-policy-storage.raml
- src/main/java/org/folio/rest/impl/RequestPoliciesAPI.java
- src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
Addressed the mismatch between content-type and description in request-policy-storage.raml.
Also return a plain text error message for 500 error instead of a JSON.
> Circstore 97 fix

- descriptors/ModuleDescriptor-template.json
- ramls/examples/request.json
- ramls/examples/requests.json
- ramls/request-storage.raml
- ramls/request.json
- sample-data/requests/interesting-times.json
- sample-data/requests/nod.json
- sample-data/requests/temeraire.json
- src/test/java/org/folio/rest/api/CancellationReasonsApiTest.java
- src/test/java/org/folio/rest/api/RequestsApiTest.java
- src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
In order to provide a finer grained expiration period for `holdShelfExpirationDate`, we need to include a time component to the field. We are also doing this for `requestExpirationDate` as well.
Since this is a breaking change the major version of the `request-storage` interface has been bumped.
> CIRCSTORE-107 - request and pick up expiration to include time

- src/main/resources/templates/db_scripts/schema.json
Currently the SQL generated by cql2pgjson cannot use the index in the database. See below for the actual sql and index. The goal of this PR is to tweak the db index to match the SQL.
```
Query: SELECT COUNT(*) FROM supertenant_mod_circulation_storage.loan  WHERE (lower(f_unaccent(loan.jsonb->>'itemId')) LIKE lower(f_unaccent('00007443-1460-410e-bd22-305abf53ed6a'))) AND (lower(f_unaccent(loan.jsonb->'status'->>'name')) LIKE lower(f_unaccent('Open')))
Index: "loan_itemid_idx_unique" UNIQUE, btree (f_unaccent(jsonb ->> 'itemId'::text)) WHERE ((jsonb -> 'status'::text) ->> 'name'::text) = 'Open'::text
```
> FOLIO-1853: tweak index so query open loan by item id can use.

- ramls/examples/loan-policies.json
- ramls/examples/loan-policy.json
- reference-data/loan-policy-storage/loan-policies/one-hour.json
- reference-data/loan-policy-storage/loan-policies/rolling.json
- src/test/java/org/folio/rest/api/LoanPoliciesApiTest.java
- src/test/java/org/folio/rest/support/builders/LoanPolicyRequestBuilder.java
Resolves: CIRCSTORE-120
Change sample loan policy records to correspond with what is expected in **mod-circulation** and **ui-circulation**.
Change _closedLibraryDueDateManagementId_ property of loan policy from "KEEP_CURRENT_DATE" to "CURRENT_DUE_DATE"
https://issues.folio.org/browse/CIRCSTORE-120
> [CIRCSTORE-120] Change sample loan policy records to expected values

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/patron-notice-policy.raml
- src/main/java/org/folio/rest/impl/CirculationRulesAPI.java
- src/main/java/org/folio/rest/impl/PatronNoticePoliciesAPI.java
- src/main/java/org/folio/support/exception/NoticePolicyInUseException.java
- src/test/java/org/folio/rest/api/CirculationRulesApiTest.java
- src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
Resolves: CIRCSTORE-119
Not allow user to delete patron notice policy if currently in use
https://issues.folio.org/browse/CIRCSTORE-119
> [CIRCSTORE-119] Not allow user to delete patron notice policy if currently in use

- descriptors/Activate-template.json
- descriptors/Install-template.json
- okapi-registration/managed-deployment/register.sh
- pom.xml
In order to improve local testing of reference and sample record loading, the managed demo script could use the install endpoint to trigger this each time the module is started.
> Use install endpoint for running managed demo CIRCSTORE-131

- src/main/java/org/folio/rest/impl/RequestExpiryImpl.java
- src/main/java/org/folio/support/ExpirationTool.java
reduce run period to "every 2 minutes" and process up to 150 expired requests
> [CIRCSTORE-133] Request Expiration Job Takes Too Long for Short Term Expiry Periods

- CODEOWNERS
To help broaden the collective ownership of this module and expand the set of folks who can review changes to this module we are introducing an initial set of code owners.
This initial set is made up of the active contributors to this module over the last year and the Tech Leads from teams actively working in this area.
> Define initial set of code owners

- pom.xml
This fixes the audit table id field that caused PK unique constraint violation on concurrent queries: [RMB-430](https://issues.folio.org/browse/RMB-430)
> CIRCSTORE-136: Update RMB to 26.2.1

- pom.xml
In order to have at least one snapshot version of the correct version published prior to formal release.
[CIRCSTORE-134](https://github.com/folio-org/mod-circulation-storage/commit/cf452b7bc62ffc94d6e6a5e5402c1abacb1d4eea) introduced compatibility breaking changes, which were correctly reflected in the interface version.
This change means that it will also be reflected in the implementation version, prior to the upcoming formal release.
> Increment major version to reflect breaking compatibility change CIRCSTORE-134

- descriptors/ModuleDescriptor-template.json
- ramls/patron-notice-policy.json
- ramls/patron-notice-policy.raml
- ramls/scheduled-notice-storage.raml
- ramls/scheduled-notice.json
- src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
- src/test/java/org/folio/rest/api/ScheduledNoticesAPITest.java
Resolves: CIRCSTORE-141
1. Add `Request Expiriation` event to patron notice policy by the following path
patron-notice-policy.json -> requestNotices -> sendOptions -> sendWhen
2. Add `triggeringEvent` property to scheduled-notice json, values: Hold Expiration, Request Expiration
https://issues.folio.org/browse/CIRCSTORE-141
https://issues.folio.org/browse/CIRC-387
> [CIRCSTORE-141] Extend patron notice policy and scheduled notice schemas

- pom.xml
9.1.0-SNAPSHOT was incorrect due to a mistake when entering the next
version during the last release
> CIRCSTORE-145 Increment version to 9.2.0-SNAPSHOT

- descriptors/ModuleDescriptor-template.json
- ramls/patron-notice-policy.json
- ramls/patron-notice-policy.raml
- src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
Add "Manual due date change" as a triggering event to loan notices in patron notice policy
Resolves: [CIRCSTORE-151](https://issues.folio.org/browse/CIRCSTORE-151)
- Add "Manual due date change" option to `sendWhen` enum in **patron notice policy** JSON schema
- Increase minor version of `patron-notice-policy-storage` interface
- Change the test to demonstrate that "Manual due date change" is an allowed option
> [CIRCSTORE-151] Add "Manual due date change" as a triggering event

- Jenkinsfile
enables kubeDeploy step on buildMvn pipeline to deploy images to ci kubernetes cluster on release/snapshot builds.
> FOLIO-2256 deploy image to ci k8s cluster on snapshot/release build

- descriptors/ModuleDescriptor-template.json
- ramls/loan-storage.raml
- ramls/loan.json
- src/test/java/org/folio/rest/api/LoansApiTest.java
- src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
This is the storage counterpart for CIRC-440. This will persist the `dueDateChangedByRecall` in the loan. This flag will indicate to circulation that a recall has been placed that has modified the due date of the loan.
> CIRCSTORE-156: add a flag for recall due date modification

- descriptors/ModuleDescriptor-template.json
- ramls/patron-notice-policy.json
- ramls/patron-notice-policy.raml
- src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
Move "Recall loanee" triggering event option from request notices to loan notices and rename it to "Item recalled". 
Resolves story: [CIRCSTORE-155](https://issues.folio.org/browse/CIRCSTORE-155)
It is needed for: [UICIRC-279](https://issues.folio.org/browse/UICIRC-279)
- Changed patron notice policy schema due to requirements
- Given PR already introduces breaking change, removed "Overdue" option from loan notices as not used and renamed "Hold Expiration" to "Hold expiration" to follow convention
- Updated tests according to schema changes
This PR should be merged together with mod-circulation PR and ui-circulation PR (not ready yet)
> [CIRCSTORE-155] Change patron notice policy schema 

- descriptors/ModuleDescriptor-template.json
- ramls/examples/patron-action-session.json
- ramls/examples/patron-action-sessions.json
- ramls/patron-action-session.json
- ramls/patron-action-session.raml
- ramls/patron-action-sessions.json
- src/main/java/org/folio/rest/impl/PatronActionSessionAPI.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/AnonymizeLoansApiTest.java
- src/test/java/org/folio/rest/api/LoansApiTest.java
- src/test/java/org/folio/rest/api/PatronActionSessionAPITest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/api/loans/LoansAnonymizationApiTest.java
- src/test/java/org/folio/rest/support/http/AssertingRecordClient.java
- src/test/java/org/folio/rest/support/http/InterfaceUrls.java
Resolves: CIRCSTORE-147, CIRCSTORE-148
1. Create DB table to store check-in/check-out session information 
2. Create CRUD API endpoints for patron action session
1. Update `AssertingRecordClient` with new field `String collectionPropertyName`
2. Add `attemptDeleteById(UUID id)` and `attemptPutById(JsonObject updateObject)` methods to `AssertingRecordClient` 
1. The name of the table and API endpoints are under discussion
1. https://issues.folio.org/browse/CIRCSTORE-147
2. https://issues.folio.org/browse/CIRCSTORE-148
> [CIRCSTORE-147, CIRCSTORE-148] Create CRUD API endpoints for patron action session

- descriptors/ModuleDescriptor-template.json
- ramls/examples/patron-action-expired-session.json
- ramls/patron-action-expired-ids-response.json
- ramls/patron-action-session.raml
- ramls/patron-action-sessions.json
- src/main/java/org/folio/rest/impl/PatronActionSessionAPI.java
- src/main/java/org/folio/support/PgClientFutureAdapter.java
- src/test/java/org/folio/rest/api/PatronActionSessionAPITest.java
Add API endpoint to retrieve all patrons Ids from patron_action_session table where last record's createdDate has expired according to configured timeout
Resolves story: https://issues.folio.org/browse/CIRCSTORE-149
- update patron-action-session.raml to support retrieving patron IDs with expired sessions
- implement `getPatronActionSessionStorageExpiredSessionPatronIds `method in `PatronActionSessionAPI`
- create tests to `PatronActionSessionAPITest`
https://issues.folio.org/browse/CIRCSTORE-149
> [Circstore-149] Create API endpoint to retrieve patron IDs with expired sessions

- descriptors/ModuleDescriptor-template.json
- increase JVM max heap default from 256mb to 384mb.  
- Increase container limit from 384mb to 512mb.
> increase default memory limits in MD

- src/main/java/org/folio/rest/impl/PatronNoticePoliciesAPI.java
- src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
Resolves: CIRCSTORE-158
1. Create BE validation for update patron notice policies
2. Create tests to test validation
1. Update `PatronNoticePoliciesAPI` with new validation for `putPatronNoticePolicyStoragePatronNoticePoliciesByPatronNoticePolicyId`
2. Update `PatronNoticePoliciesApiTest` to test validation changes
https://issues.folio.org/browse/CIRCSTORE-158
> CIRCSTORE-158 add BE validation for update patron notice policies

- README.MD
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/request-storage-batch.raml
- ramls/requests-batch.json
- src/main/java/org/folio/rest/impl/RequestsAPI.java
- src/main/java/org/folio/rest/impl/RequestsBatchAPI.java
- src/main/java/org/folio/rest/impl/util/RequestsApiUtil.java
- src/main/java/org/folio/service/BatchResourceService.java
- src/main/java/org/folio/service/request/RequestBatchResourceService.java
- src/test/java/org/folio/rest/api/RequestBatchAPITest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
https://issues.folio.org/browse/CIRCSTORE-164: Create new request batch update endpoint.
Implemented `POST` `/request-storage-batch/requests` endpoint that allows to execute request updates **sequentially** within the **same transaction**. Any failures occurred during update will cause transaction to be rejected.
```
{
"requests": [
{
"id" : "rq1 id",
// position attribute removed
...
},
{
"id" : "rq2 id",
// position attribute removed
...
},
{
"id" : "rq1 id",
"position": 2
...
},
{
"id" : "rq2 id",
"position": 1
...
}
],
// Not required here, as 'Same' is default value
"transactionMode": "Same"
}
```
> CIRCSTORE-164: Implement request batch update API.

- reference-data/circulation-rules-storage/single-rule.json
New default lost item fee policies added to the 'single-rule.json' file.
**This change should be merged with CIRC-467** (PR:https://github.com/folio-org/mod-circulation/pull/399)
This PR is similar to the previous PR regarding adding a new default overdue fine policy 'o', which was reviewed and merged: https://github.com/folio-org/mod-circulation-storage/pull/215
> CIRCSTORE-171: Create default lost item fees policy.

- Dockerfile
- descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
> CIRCSTORE-173 FOLIO-2358 manage container memory

- src/main/resources/templates/db_scripts/schema.json
Change dictionary from english to simple.
The upgrade script drops the old index with 'english' dictionary.
RMB only (re-)creates the index with the correct 'simple' dictionary if
an index with that name does not exist.
> CIRC-598: Fix loan.userId fullTextIndex

- src/main/resources/templates/db_scripts/schema.json
BNCF needs them for open loans queries:
https://folio-project.slack.com/archives/C9BBWRCNB/p1579860339261200
"caseSensitive" and "removeAccents" for username are taken from the definition in mod-users:
https://github.com/folio-org/mod-users/blob/v16.0.0/src/main/resources/templates/db_scripts/schema.json#L80
All other indexes are UUIDs or dates that are case insensitive and do not require accent removal.
> CIRCSTORE-184: Add several loan indexes.

- descriptors/ModuleDescriptor-template.json
- ramls/request-storage-batch.raml
- ramls/request-storage.raml
- ramls/request.json
- ramls/uuid.json
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/RequestsApiTest.java
- src/test/java/org/folio/rest/support/builders/RequestItemSummary.java
- src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
https://issues.folio.org/browse/CIRCSTORE-181: Backend: Search for requests by instance ISBN (or other Identifiers).
* Add `item.identifiers` array;
* Add full text indexes for the new property;
* Add missed indexes for request search box. The query is following:
`((requesterId=="900" or requester.barcode="900*" or item.title="900*" or item.barcode="900*" or itemId=="900")) sortby requestDate`, so need indexes for:
* requesterId
* requester.barcode
* item.title
* item.barcode
* itemId
> CIRCSTORE-181: Store instance identifiers in request.

- descriptors/ModuleDescriptor-template.json
- ramls/check-in-storage.raml
- ramls/check-in.json
- ramls/examples/check-in.json
- ramls/examples/check-ins.json
- src/test/java/org/folio/rest/api/CheckInStorageApiTest.java
- src/test/java/org/folio/rest/support/builders/CheckInBuilder.java
https://issues.folio.org/browse/CIRCSTORE-196: Store additional properties in check-in-storage.
Add properties needed for in-house use:
* itemStatus
* itemLocationId;
* requestQueueSize;
> CIRCSTORE-196: Store additional check-in properties for in-house use.

- descriptors/ModuleDescriptor-template.json
- ramls/loan-storage.raml
- ramls/loan.json
- src/test/java/org/folio/rest/api/LoansApiTest.java
- src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
Reverts folio-org/mod-circulation-storage#240
**Reason:**
According to requirements, we don't need markedMissingDate property for a loan
> Revert "CIRCSTORE-201 Add markedMissingDate property to a loan"

- descriptors/ModuleDescriptor-template.json
- ramls/examples/loan.json
- ramls/loan-storage.raml
- ramls/loan.json
- src/test/java/org/folio/rest/api/LoansApiTest.java
- src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
https://issues.folio.org/browse/CIRCSTORE-208
Follow-up to [CIRCSTORE-157](https://github.com/folio-org/mod-circulation-storage/pull/194) which added a new field itemEffectiveLocationAtCheckOut. This field name was renamed in mod-circulation; this issue is to propagate that rename to mod-circulation-storage.
> CIRCSTORE-208: rename itemEffectiveLocationAtCheckOut

- src/main/resources/templates/db_scripts/schema.json
request.requestType is an enum with these values: ["Hold", "Recall", "Page"]
The correct match operator is the field matching `==`
The existing "ginIndex" should be removed and a b-tree "index" created.
It should be case insensitive (for usability, the same as other request
b-tree indexes) and accents sensitive (we don't expect "Höld" searches.
The new index will also provide better totalRecords estimations resolving
https://issues.folio.org/browse/CIRCSTORE-210 .
> CIRCSTORE-219: Create request.requestType b-tree index

- pom.xml
- src/test/java/org/folio/rest/api/CheckInStorageApiTest.java
- src/test/java/org/folio/rest/api/LoansApiTest.java
- src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
Updating RMB from 30.0.1 to RMB 30.2.4 fixes
https://issues.folio.org/browse/CIRCSTORE-210 "Requests -Filtering
by Request Type returns (Total Records = 1000) when there are more"
because it includes these fixes:
* [RMB-637](https://issues.folio.org/browse/RMB-637) Run ANALYZE after index (re-)creation
* [RMB-645](https://issues.folio.org/browse/RMB-645) Use where-only clause for the "count query"
* [RMB-639](https://issues.folio.org/browse/RMB-639) Unexpected breaking changes streamGet and getWithOptimizedSql
https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-302 advises:
> https://issues.folio.org/browse/RMB-652 error message "may not be null" changed to "must not be null" (hibernate-validator)
>  CIRCSTORE-220: Upgrade to raml-module-builder (RMB) 30.2.4 

- pom.xml
RMB 30.2.6 release notes -
https://github.com/folio-org/raml-module-builder/releases/tag/v30.2.6
* [RMB-701](https://issues.folio.org/browse/RMB-701) Update to [Vert.x 3.9.2](https://github.com/vert-x3/wiki/wiki/3.9.2-Release-Notes), fixing WebClient request timeout races
* [RMB-700](https://issues.folio.org/browse/RMB-700) NPE when RestVerticle calls LogUtil.formatStatsLogMessage
* [RMB-677](https://issues.folio.org/browse/RMB-677) Close PostgreSQL connection after invalid CQL failure
> CIRCSTORE-237: Upgrade to raml-module-builder (RMB) 30.2.6

- pom.xml
RMB 31.1.5 provides
* RMB-750 Change lock for "tuple concurrently updated" when upgrading Q2 to Q3 (REVOKE)
> CIRCSTORE-252: Upgrade to RMB 31.1.5

- descriptors/ModuleDescriptor-template.json
- ramls/patron-notice-policy.json
- ramls/patron-notice-policy.raml
- src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
Add new triggering events for "Aged to lost" item status.
Resolves story: [CIRCSTORE-248](https://issues.folio.org/browse/CIRCSTORE-248)
- Added new triggering events according to the story
> [CIRCSTORE-248] New triggering events for 'aged to lost' item status and lost item fees/fines

- src/main/java/org/folio/rest/impl/AnonymizeStorageLoansAPI.java
- src/test/java/org/folio/rest/api/AnonymizeLoansApiTest.java
- src/test/java/org/folio/rest/support/ApiTests.java
- src/test/java/org/folio/rest/support/http/InterfaceUrls.java
- src/test/java/org/folio/rest/support/matchers/LoanHistoryMatchers.java
https://issues.folio.org/browse/CIRCSTORE-260 - Anonymize all versions of loans when anonymizing
* Fix the SQL query so that the loan history is also anonymized.
> CIRCSTORE-260: Anonymize loan history entries as well as loan.

- descriptors/ModuleDescriptor-template.json
- ramls/examples/loan-policy.json
- ramls/loan-policy-storage.raml
- ramls/loan-policy.json
- src/test/java/org/folio/rest/api/LoanPoliciesApiTest.java
- src/test/java/org/folio/rest/support/builders/LoanPolicyRequestBuilder.java
Provide the storage for the Boolean and Period representing the Alternate Recall Return and Alternate Recall Return Interval.
Resolves: https://issues.folio.org/browse/CIRCSTORE-257
Update the loan-policy raml and its respective version.
Update the appropriate examples.
Update the relevant tests.
I also noticed that the example loan policy could be more thorough of an example.
> CIRCSTORE-257: Loan policy: Allow recalls to extend overdue loans

- pom.xml
- src/test/java/org/folio/rest/api/LoansApiTest.java
I went through the document linked in the description of this issue
and applied all the noted changes.  Most of them had already been done,
i just added a few things that seem to have been missed.  Despite the
name of this issue, the fixes for logging seem to be in version 32,
so I'm not sure this will actually impact any problems this module
is having with logging.
I also had a test failing on build.  It looked to me like the date
generation for the two loans in this test were a bit screwy-the date
labeled "tomorrow" was actually today.  I tweaked this test a bit
so that one loan was indeed set with a date one day from the present
and the other a date one day in the past, then set it to look for
anything with a date greater than the present day.  That seems to
work.
refs: …
> CIRCSTORE-263: Broken logging for mod-circulation-storage

- src/main/resources/templates/db_scripts/schema.json
Add two b-tree indexes on the fields patronId and actionType that are missing when processing patron notices.
> added patronId b-tree index on patron_action_session table

- pom.xml
[CIRCSTORE-265](https://issues.folio.org/browse/CIRCSTORE-265) - Pickup expired not showing in Circulation log
* Updated pubsub client to 2.0.2
> CIRCSTORE-265 - Pickup expired not showing in Circulation log

- src/main/resources/templates/db_scripts/add_staff_slips_hold_transit.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/api/migration/StaffSlipsHoldTransitMigrationScriptTest.java
- src/test/java/org/folio/rest/api/migration/StaffSlipsMigrationTestBase.java
- src/test/java/org/folio/rest/api/migration/StaffSlipsPickRequestMigrationScriptTest.java
The reference data includes four slips (hold, pick-slip,
request-delivery, and transit) but only two (pick-slip,
request-delivery) were included in migrations. This meant new tenants
would have all four slips available but tenants migrated from previous
releases would only have two.
Refs [CIRCSTORE-273](https://issues.folio.org/browse/CIRCSTORE-273)
> CIRCSTORE-273 include migration for missing staff slips

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/CancellationReasonsAPI.java
- src/main/java/org/folio/rest/impl/FixedDueDateSchedulesAPI.java
- src/main/java/org/folio/service/PubSubPublishingService.java
- src/main/java/org/folio/service/PubSubRegistrationService.java
- src/test/java/org/folio/rest/api/AnonymizeLoansApiTest.java
- src/test/java/org/folio/rest/api/RequestsApiTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/support/MockServer.java
* Upgrades to RMB 33.0.0 and Vert.x 4.1.0.CR1
* Upgrades the pub-sub client as it needs to use the same version of RMB (2.x includes breaking changes, so code needed to be changed)
* The `unregisterModule` method is unused so has been removed
* Removing the `embed_postgres` command line parameter makes this a breaking compatibility change
> Upgrade to RMB 33.0.0 CIRCSTORE-280

- pom.xml
Update `mod-pubsub-client` dependency to v2.3.0. Resolves [CIRCSTORE-285](https://issues.folio.org/browse/CIRCSTORE-285).
> [CIRCSTORE-285] Update mod-pubsub-client to v2.3.0

- CODEOWNERS
As the module is maintained by multiple teams the review requests generated by the code owners definition leads to unnecessary notifications that slow down the review process as folks start to ignore them
> Remove code owners CIRCSTORE-289

- pom.xml
Fixes loan.userId index usage in CQL query.
Update RMB from to 33.1.1.
Update Vert.x from 4.1.0.CR1 to 4.2.1.
Update Spring from 5.2.7 to 5.2.18.
Update mod-pubsub-client from 2.3.0 to 2.4.0.
Move <properties> section to top of pom.xml for readability.
Remove FOLIO forks of vertx-sql-client and vertx-pg-client,
they are no longer needed: https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-331
Updating RMB fixes the loan.userId query because of
https://issues.folio.org/browse/RMB-864 "Ignore deleted index in schema.json".
> CIRCSTORE-304: RMB 33.1.1, Vert.x 4.2.1, Spring 5.2.18, PubSub 2.4.0

- Jenkinsfile
- README.MD
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-circulation-storage section of API documentation will be automatically reconfigured tomorrow:
https://dev.folio.org/reference/api/#explain-gather-config
> FOLIO-3231 Use new api-lint and api-doc CI facilities

- src/main/resources/templates/db_scripts/schema.json
Resolves [CIRCSTORE-321](https://issues.folio.org/browse/CIRCSTORE-321).
In order to build Items In Transit Report mod-circulation needs to find loans with `"itemStatus": "In transit"` by a list of `itemId`'s:
```
/loan-storage/loans?query=itemId==("b047195f-31b4-43e6-bf80-9bb2e37ce06a" or "6717378c-5808-4c04-a777-ad84690da568" or [... more ids here ...] or "9ac35413-a6bd-4569-a141-e6718c57b830") and itemStatus=="In transit"&limit=2147483647
```
which is then transformed into a DB query within mod-circulation-storage:
```
EXPLAIN ANALYZE SELECT jsonb,id FROM diku_mod_circulation_storage.loan
WHERE (((((((((((((((((((((((((((((((((((((((((((((((((
(lower(diku_mod_circulation_storage.f_unaccent(loan.jsonb->>'itemId')) LIKE lower(diku_mod_circulation_storage.f_unaccent('b047195f-31b4-43e6-bf8 …
```
> [CIRCSTORE-321] Create likeIndex for itemId to improve performance of Items In Transit Report

- pom.xml
mod-circulation-storage uses both log4j implementation and slf4j implementation for logging.
RMB based modules use log4j for logging. Therefore slf4j-log4j12/slf4j-api should be replaced by log4j-slf4j-impl so that only log4j implementation is used for logging while providing both interfaces (log4j and slf4j).
mod-circulation-storage uses org.slf4j:slf4j-log4j12@1.7.13 that requires log4j:log4j@1.2.17 that has many security vulnerabilities; after a rough skim I don't see that mod-circulation-storage is affected, but using recent versions of logging libraries stops security scanners from reporting false positives.
Known issues of log4j:log4j@1.2.17:
* https://nvd.nist.gov/vuln/detail/CVE-2022-23307
* https://nvd.nist.gov/vuln/detail/CVE-2022-23305
* …
> CIRCSTORE-325: Replace slf4j-log4j12/slf4j-api by log4j-slf4j-impl

- ramls/patron-notice-policy.json
- ramls/scheduled-notice.json
- src/test/java/org/folio/rest/api/ScheduledNoticesAPITest.java
[CIRCSTORE-339](https://issues.folio.org/browse/CIRCSTORE-339) 
Title Level Request  expiration should be created 
Approach
TITLE_REQUEST_EXPIRATION is added as an element 
Learning
Learned the way deeper how scheduler and notices work.
> CIRCTSTORE-339: Expiration notice not being sent when template selected in TLR settings

- src/main/java/org/folio/service/tlr/TlrDataMigrationService.java
- src/test/java/org/folio/rest/api/TenantRefApiTests.java
Use valid default UUID (version 4, variant 1) compliant with `uuid.schema`.
https://issues.folio.org/browse/CIRCSTORE-340
> [CIRCSTORE-340] use valid default UUID

- descriptors/ModuleDescriptor-template.json
- ramls/actual-cost-record-storage.raml
- ramls/actual-cost-record.json
- ramls/examples/actual-cost-record.json
- src/test/java/org/folio/rest/api/ActualCostRecordAPITest.java
- Add expirationDate field (date-time), not required.
It'll be used by a timer in mod-circulation that will close loans for items that were aged to lost or declared lost with actual cost in the policy, but Lost Item Fee wasn't charged during a period specified in the policy.
Resolves: [CIRCSTORE-349](https://issues.folio.org/browse/CIRCSTORE-349)
> CIRCSTORE-349 add expirationDate to actualCostRecord

- pom.xml
- src/test/java/org/folio/rest/api/StorageTestSuite.java
Update `testcontainer` and `confluentinc/cp-kafka` so it can build on arm64 machine.
[CIRCSTORE-355](https://issues.folio.org/browse/CIRCSTORE-355)
> CIRCSTORE-355: Allow compile and build on ARM64 machine

- descriptors/ModuleDescriptor-template.json
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-circulation-storage uses holdings-storage and item-storage APIs, but not instance-storage API.
mod-circulation-storage is not affected because the incompatible change is in the DELETE all records APIs only that is not used by mod-circulation-storage.
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json
> CIRCSTORE-357: Support holdings-storage 6.0, item-storage 10.0

- ramls/actual-cost-record.json
- src/test/java/org/folio/rest/api/ActualCostRecordAPITest.java
mod-circulation attempts to create Actual Cost Records without and ID, which is required according to its schema. This violation of schema's requirements causes [CIRC-1622](https://issues.folio.org/browse/CIRC-1622) and [CIRC-1623](https://issues.folio.org/browse/CIRC-1623). One way to fix this issue is to change the schema to make the ID optional, since it is added to all stored records automatically.
[CIRCSTORE-361](https://issues.folio.org/browse/CIRCSTORE-361)
> CIRCSTORE-361 Make actual cost record id optional

- pom.xml
Upgrading to Vertx > 4.3.1 breaks KafkaAdminClientServiceTest
[CIRCSTORE-363](https://issues.folio.org/browse/CIRCSTORE-363)
> CIRCSTORE-363 Upgrade to RMB 35.0.0 and Vertx 4.3.1

- src/main/resources/templates/db_scripts/schema.json
This should improve check-in performance when TLR feature is enabled.
Resolves: [CIRCSTORE-402](https://issues.folio.org/browse/CIRCSTORE-402)
- add 'instanceId' and 'expirationDate' b-tree indexes;
- update 'pickupServicePointId' index with "removeAccents": true flag;
> CIRCSTORE-402 Add b-tree indexes to DB schema

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- README.MD
- ramls/circulation-rules-storage.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 CIRCSTORE-415 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- descriptors/ModuleDescriptor-template.json
- ramls/patron-action-session.json
- ramls/patron-action-session.raml
- ramls/scheduled-notice-storage.raml
- ramls/scheduled-notice.json
- src/test/java/org/folio/rest/api/PatronActionSessionAPITest.java
- src/test/java/org/folio/rest/api/ScheduledNoticesAPITest.java
Support new functionality introduced in [CIRC-1726](https://issues.folio.org/browse/CIRC-1726) by adding an optional UUID property `sessionId` to both scheduled notice and patron action session schema.
Resolves [CIRCSTORE-421](https://issues.folio.org/browse/CIRCSTORE-421)
> CIRCSTORE-421 Add sessionId to scheduled notice and patron action session

- src/main/java/org/folio/service/migration/AbstractRequestMigrationService.java
- src/main/java/org/folio/support/PgClientFutureAdapter.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/api/TenantRefApiTests.java
- Update calling existing RMB "Read" methods to use new RMB Readonly APIs
Resolves: [CIRCSTORE-359](https://issues.folio.org/browse/CIRCSTORE-359)
> [CIRCSTORE-359] Use new RMB readonly APIs

- descriptors/ModuleDescriptor-template.json
- ramls/cancellation-reason.json
- ramls/cancellation-reason.raml
- ramls/examples/cancellation-reason.json
- ramls/examples/cancellation-reasons.json
- src/test/java/org/folio/rest/api/CancellationReasonsApiTest.java
Resolves: [CIRCSTORE-431](https://issues.folio.org/browse/CIRCSTORE-431) Modify circulation dtos to include source field.
This table describes what setting we are going to implement in Consortium Manager:
https://wiki.folio.org/display/FOLIJET/Consortium+manager+settings
So for _mod-circulation-storage_ it is _cancellation reason_.
Setting created in Consortium Manager will have value _'Consortium'_ and we will add validation to prevent updating them
> [CIRCSTORE-431] Modify circulation dtos to include source field.

- src/main/java/org/folio/rest/client/ConfigurationClient.java
- src/main/java/org/folio/rest/impl/RequestExpiryImpl.java
- src/test/java/org/folio/rest/api/RequestExpirationApiTest.java
- src/test/java/org/folio/rest/support/ApiTests.java
It was decided that the best way to handle this was to create a alternate method in the configuration client that would return a default settings object if the TLR settings have not been initialized.  The default method assumes TLR should be disabled.  This will allow the expiration process to run if the settings have not been set.
> CIRCSTORE-412: Request does not change status when TLR settings not set

- ramls/circulation-rules.json
- src/main/java/org/folio/rest/impl/CirculationRulesAPI.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/CirculationRulesApiTest.java
CIRCSTORE-410 (https://issues.folio.org/browse/CIRCSTORE-410)
When I save the circulation rules in Settings > Circulation > Circulation rules, I want the associated metadata object to be updated with the logged in user info for last update date and last update by.
1. Metadata added in schema.json 
2. Code updated 
3. Test case updated 
Output :
> Circstore 410

- src/main/resources/templates/db_scripts/schema.json
From looking at the schema file, it *looks* like this is the way to add gindexes to fields in the module tables.  Let me know if not-the only other way I know of to do this would be a database script.
> CIRCSTORE-411: Slow response for CQL searching - requests

- descriptors/ModuleDescriptor-template.json
- ramls/actual-cost-record.json
Covers [CIRCSTORE-447](https://issues.folio.org/browse/CIRCSTORE-447)
**Purpose**
Goal of this PR is to allow creation of Actual cost records with no Expiration date if in "Lost Item policy" option "For lost items not charged a fee/fine, close the loan after" not set.
**Approach**
expirationDate field removed from required fields
> CIRCSTORE-447 Cannot create Actual cost record without Expiration date

- descriptors/ModuleDescriptor-template.json
- ramls/request-policy-storage.raml
- ramls/service-point.json
- ramls/service-points.json
- ramls/time-period.json
- src/main/java/org/folio/rest/client/InventoryStorageClient.java
- src/main/java/org/folio/rest/client/OkapiClient.java
- src/main/java/org/folio/rest/impl/RequestPoliciesAPI.java
- src/main/java/org/folio/service/policy/RequestPolicyValidationService.java
- src/main/java/org/folio/support/AsyncUtils.java
- src/main/java/org/folio/support/ErrorCode.java
- src/main/java/org/folio/support/exception/HttpException.java
- src/main/java/org/folio/support/exception/ValidationException.java
- src/test/java/org/folio/rest/api/EventConsumerVerticleTest.java
- src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
- src/test/java/org/folio/rest/client/OkapiClientTest.java
- src/test/java/org/folio/rest/support/matchers/ValidationErrorMatchers.java
- src/test/java/org/folio/support/AsyncUtilsTest.java
Do not allow saving or updating a request policy when at least one of the configured allowed pickup service points does not exist or is not explicitly marked as a pickup location.
Resolves [CIRCSTORE-429](https://issues.folio.org/browse/CIRCSTORE-429).
> CIRCSTORE-429: Validate allowed service points on POST and PUT

- ramls/service-point.json
- src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
This is a follow-up PR for [CIRCSTORE-429](https://issues.folio.org/browse/CIRCSTORE-429). Once #419 was merged, it became impossible to create or update a request policy when an explicitly allowed pickup service point contains staff slips configuration. This issue was caused by a conflict between JSON-schemas of a full-fledged staff slip and its reduced representation within service point schema. Removing `staffSlips` property from service point schema pushes staff slips into `additionalProperties` field of a generated service point class, which resolves the issue.
> CIRCSTORE-429: Remove staff slips from service point schema

- src/main/java/org/folio/service/policy/RequestPolicyValidationService.java
- src/main/java/org/folio/support/exception/ValidationException.java
- src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
Return only one validation error with text "One or more Pickup locations are no longer available" when trying to create or update a request policy with invalid allowed service points.
Resolves [CIRCSTORE-451](https://issues.folio.org/browse/CIRCSTORE-451).
> CIRCSTORE-451: Return single error for invalid request policy

- src/main/resources/templates/db_scripts/insertEmptyCirculationRulesRecord.sql
Create unique constraints for column `lock` in table `circulation_rules` only if they do not exist, otherwise every time the script is executed, a new pair of constraints is created and added to existing ones.
Resolves [CIRCSTORE-445](https://issues.folio.org/browse/CIRCSTORE-445).
> CIRCSTORE-445: Create constraints only if they don't exist

- descriptors/ModuleDescriptor-template.json
- ramls/scheduled-notice-storage.raml
- ramls/scheduled-notice.json
Upcoming processing of reminder fees in mod-circulation will require an new triggering event type for scheduled notices - "Due date - with reminder fee". Reminder fees are a special case of overdue notices, and require an event type that distinguish them from due date notices. 
API version of scheduled-notice-storage is upped a minor for this change.
> CIRCSTORE-452

- pom.xml
- src/main/java/org/folio/rest/impl/AnonymizeStorageLoansAPI.java
- src/main/java/org/folio/service/loan/LoanService.java
- src/test/java/org/folio/rest/api/TlrFeatureToggleJobAPITest.java
[CIRCSTORE-494](https://folio-org.atlassian.net/browse/CIRCSTORE-494)
Upgrade to RMB 35.2.0, Vertx 4.5.5, Spring 6.1.5
According to https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-352, changed javax.validation package to jakarta.validation.
> CIRCSTORE-494 Upgrade to RMB 35.2.0, Vertx 4.5.5, Spring 6.1.5

- NEWS.md
- pom.xml
Covers: [CIRCSTORE-499](https://folio-org.atlassian.net/browse/CIRCSTORE-499)
Upgrade folio-kafka-wrapper to 3.1.1, org.aspectj to 1.9.22 to fix error with  Kafka Topic, when Tenant Collection Is Enabled, Module May Delete Topic For All Tenants
> CIRCSTORE-499 Upgrade folio-kafka-wrapper, org.aspectj versions

- descriptors/ModuleDescriptor-template.json
mod-circulation-storage consumes interface `configuration` provided by mod-configuration, but does not declare this dependency in its `ModuleDescriptor.json`.
[CIRCSTORE-505](https://folio-org.atlassian.net/browse/CIRCSTORE-505)
> CIRCSTORE-505: Add required interface "configuration"

- descriptors/ModuleDescriptor-template.json
- ramls/loan-storage.raml
- ramls/loan.json
- src/test/java/org/folio/rest/api/LoansApiTest.java
- src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
Purpose: https://folio-org.atlassian.net/browse/CIRCSTORE-506 
Approach: added isDcb flag in loan.json and added few testcases for loan creation when is isDcb feild is present with values true or false
> Circstore 506

- descriptors/ModuleDescriptor-template.json
- ramls/circulation-setting.json
- ramls/circulation-settings-storage.raml
- ramls/circulation-settings.json
- ramls/examples/circulation-setting.json
- ramls/examples/circulation-settings.json
- src/main/java/org/folio/persist/CirculationSettingsRepository.java
- src/main/java/org/folio/rest/impl/CirculationSettingsAPI.java
- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/java/org/folio/service/CirculationSettingsService.java
- src/main/java/org/folio/service/event/EntityChangedEventPublisherFactory.java
- src/main/java/org/folio/support/ModuleConstants.java
- src/main/java/org/folio/support/kafka/topic/CirculationStorageKafkaTopic.java
- src/main/resources/postgres-conf.json
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/CirculationSettingsAPITest.java
- src/test/java/org/folio/rest/support/http/InterfaceUrls.java
- src/test/java/org/folio/service/kafka/topic/KafkaAdminClientServiceTest.java
Covers: [CIRCSTORE-509](https://folio-org.atlassian.net/browse/CIRCSTORE-509)
**Purpose**
Create a new API (GET, POST, PUT, DELETE) for storing circulation settings . It will be used for syncing ECS TLR setting (MODTLR-44) through consortia publications.
> CIRCSTORE-509: Create CRUD API for storing circulation settings

- src/test/java/org/folio/rest/api/CirculationSettingsAPITest.java
Purpose: https://folio-org.atlassian.net/browse/CIRCSTORE-512
Approach: added a new test case for persisting and retrieving EnableRequestPrintDetailsSetting.
> CIRCSTORE-512 added test case for EnableRequestPrintDetailsSetting

- ramls/request-queue-reordering.json
- ramls/request-storage-batch.raml
- src/main/java/org/folio/rest/impl/RequestsBatchAPI.java
- src/main/java/org/folio/service/BatchResourceService.java
- src/main/java/org/folio/service/event/EntityChangedEventPublisherFactory.java
- src/main/java/org/folio/service/request/RequestBatchResourceService.java
- src/main/java/org/folio/support/kafka/topic/CirculationStorageKafkaTopic.java
- src/test/java/org/folio/rest/api/RequestBatchAPITest.java
- src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java
- src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
- src/test/java/org/folio/service/kafka/topic/KafkaAdminClientServiceTest.java
##Purpose
When the UI reorders requests, it calls the /circulation/requests/queue/instance/{instanceId}/reorder endpoint 
This endpoint calls /request-storage-batch/requests from mod-circulation-storage, and after successful reordering, mod-circulation-storage should publish a Kafka request-batch-update event. The event's payload must include the instanceId and the IDs of the reordered requests
Resolves: [CIRCSTORE-521](https://folio-org.atlassian.net/browse/CIRCSTORE-521)
> [CIRCSTORE-521] Publish request batch event when requests are reordered

- descriptors/ModuleDescriptor-template.json
- ramls/request.json
- src/main/java/org/folio/rest/impl/PrintEventsApi.java
- src/main/java/org/folio/service/PrintEventsService.java
- src/test/java/org/folio/rest/api/PrintEventsAPITest.java
https://folio-org.atlassian.net/browse/CIRC-2138
> CIRC-2138: added sync for request table post PrintEvent insertions

- NEWS.md
- descriptors/ModuleDescriptor-template.json
[CIRCSTORE-533](https://folio-org.atlassian.net/browse/CIRCSTORE-533)
Upgrade the API version in the ModuleDescriptor-template.json:
-`holdings-storage 8.0`
> [CIRCSTORE-533] Upgrade "holdings-storage" API

- ramls/request.json
- src/test/java/org/folio/rest/api/RequestsApiTest.java
- src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
CIRCSTORE-542
Add Intermediate phase for ECS requests
> CIRCSTORE-542 Add Intermediate ECS request phase

- NEWS.md
- pom.xml
- ramls/request.json
- src/test/java/org/folio/rest/api/RequestsApiTest.java
- src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
Resolves: [CIRCSTORE-554](https://folio-org.atlassian.net/browse/CIRCSTORE-554)
> CIRCSTORE-554 Release 17.3.2

- src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/CIRCSTORE-553
Bump the "fromModuleVersion" of createIsbnFunctions.sql from "12.3.0" to "17.3.4" so that the "CREATE OR REPLACE FUNCTION" updates ("REPLACE") the function in existing installations.
> CIRCSTORE-553: Update normalize_isbns to have full schema path

- descriptors/ModuleDescriptor-template.json
- ramls/loan-policy-storage.raml
- ramls/loan-policy.json
- ramls/loan-storage.raml
- ramls/loan.json
- src/test/java/org/folio/rest/api/CirculationRulesApiTest.java
Some libraries have materials that patrons can loan for a given period but cannot bring out of the library. Instead items must be picked up and put back on a hold shelf with each day of use. Each use must be registered to keep track of the items and for statistics. See also [UXPROD-1835](https://folio-org.atlassian.net/browse/UXPROD-1835). 
This PR adds new, optional properties to the loan policy and the loan. In the loan policy it can be specified that the items under the policy must be used at the location. The loan has new properties for registering the usage at location. 
The processing of the new properties will happen in mod-circulation, [CIRC-2308](https://folio-org.atlassian.net/browse/UXPROD-1835).
The version numbers of `loan-storage` and `loan-policy-storage` are bumped a minor …
> CIRCSTORE-578 use at location
