ramls/examples/loan-policies.json, ramls/examples/loan-policy.json, ramls/examples/loans.json, ramls/loan-policy-storage.raml, ramls/loan-storage.raml, ramls/schema/loan-policies.json, ramls/schema/loan-policy.json, ramls/schema/loans.json
=> FOLIO-351 ramls tidy 1

pom.xml
https://github.com/mojohaus/aspectj-maven-plugin/pull/20
=> update aspectj-maven-plugin to 1.10 to make it work in eclipse

Jenkinsfile
=> Add "Publish Module Descriptor" step to Jenkinsfile

Dockerfile, descriptors/DeploymentDescriptor-environment-template.json, descriptors/DeploymentDescriptor-template.json, destroy-demo-db.sh, destroy-test-db.sh, pom.xml, registration/activate.json, src/main/java/org/folio/rest/impl/LoanPoliciesAPI.java, src/main/java/org/folio/rest/impl/LoansAPI.java, src/main/java/org/folio/rest/impl/RequestsAPI.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, stop-managed-demo.sh
=> FOLIO-813 artifact mod- prefix

Jenkinsfile, NEWS.md, ramls/loan-rules.json
=> FOLIO-351 whitespace tidy 1

ramls/fixed-due-date-schedule.json, ramls/loan.json, ramls/request.json
Enable upper-case in first segment.
=> FOLIO-972 Improve UUID-like regex

NEWS.md, src/main/java/org/folio/rest/impl/LoansAPI.java, src/test/java/org/folio/rest/api/LoansApiHistoryTest.java
Limit/offset only set when the query is set as well
https://issues.folio.org/browse/CIRCSTORE-58
=> CIRCSTORE-58

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/examples/staff-slip.json, ramls/examples/staff-slips.json, ramls/staff-slip.json, ramls/staff-slips.json, ramls/staff-slips.raml, src/main/java/org/folio/rest/impl/StaffSlipsAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/StaffSlipsApiTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/support/builders/StaffSlipRequestBuilder.java
Resolves [CIRCSTORE-52](https://issues.folio.org/browse/CIRCSTORE-52)
Added CRUD for the Staff Slip entity with the following properties:
name (string, unique, required)
description (text)
active (boolean, default true)
template (text)
metadata
=> Circstore 52

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/cancellation-reason.json, ramls/cancellation-reason.raml, ramls/cancellation-reasons.json, ramls/examples/cancellation-reason.json, ramls/examples/cancellation-reasons.json, ramls/request.json, src/main/java/org/folio/rest/impl/CancellationReasonsAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/CancellationReasonsApiTest.java, src/test/java/org/folio/rest/api/RequestsApiTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
Covers https://issues.folio.org/browse/CIRCSTORE-47
=> CIRCSTORE-47

README.MD, ramls/staff-slips.raml, src/main/java/org/folio/rest/impl/CancellationReasonsAPI.java, src/test/java/org/folio/rest/api/CancellationReasonsApiTest.java, src/test/java/org/folio/rest/api/LoansApiHistoryTest.java, src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
Cleaned up the easy new code-style parts. Not addressed the recently introduced tabs.
=> FOLIO-351 whitespace tidy 3

NEWS.md, ramls/cancellation-reasons.json, ramls/fixed-due-date-schedules.json, ramls/loan-policies.json, ramls/loans.json, ramls/request.json, ramls/requests.json, ramls/staff-slips.json, src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
Some of the easier descriptions.
=> CIRCSTORE-75 schema descriptions 1

ramls/request.json
https://issues.folio.org/browse/CIRCSTORE-81
=> Deprecate the patron group properties for users related to a request

.gitignore, descriptors/ModuleDescriptor-template.json, ramls/examples/patron-notice-policy.json, ramls/patron-notice-policy.json, ramls/patron-notice-policy.raml, src/main/java/org/folio/rest/impl/PatronNoticePoliciesAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
1. Create Patron Notice Policy schema
2. Implement Patron Notice Policy POST and PUT endpoints
3. Write POST and PUT API tests
4. Stop embedded postgres in API tests
5. Update gitignore - add *.iml
=> CIRCSTORE-89: Patron Notice Policy POST & PUT API Endpoints

descriptors/ModuleDescriptor-template.json, ramls/patron-notice-policies.json, ramls/patron-notice-policy.raml, src/main/java/org/folio/rest/impl/PatronNoticePoliciesAPI.java, src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
Circulation storage - get patron notice policy collection.
Jira link: [CIRCSTORE-91](https://issues.folio.org/browse/CIRCSTORE-91)
=> CIRCSTORE-91: Patron notice policy - Get All

descriptors/ModuleDescriptor-template.json, ramls/patron-notice-policy.raml, src/main/java/org/folio/rest/impl/PatronNoticePoliciesAPI.java, src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
**Purpose** 
Backend: Delete Patron Notice Policy API Endpoint
**Links**
[CIRCSTORE-90](https://issues.folio.org/browse/CIRCSTORE-90)
=> CIRCSTORE-90 Add "Delete Patron Notice Policy" API Endpoint

descriptors/ModuleDescriptor-template.json, ramls/request-storage.raml, ramls/request.json
Update the request status enum to include "Open - In transit" via CIRCSTORE-101.
=> Add "Open - In transit" status to request.json

README.MD, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/circulation-rules-storage.raml, ramls/circulation-rules.json, ramls/examples/circulation-rules.json, ramls/examples/loan-rules.json, reference-data/circulation-rules-storage/use-example-for-everything.json, reference-data/import.sh, reference-data/loan-rules-storage/use-example-for-everything.json, src/main/java/org/folio/rest/impl/CirculationRulesAPI.java, src/main/resources/templates/db_scripts/insertEmptyCirculationRulesRecord.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/CirculationRulesApiTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
Replaced the loan-rules-storage interface with a
circulation-rules-storage interface.
Updated the sample rules to reflect current circulation rules practices.
Refactored loan rules to circulation rules.
=> Refactored to circulation-rules-storage

reference-data/import.sh, reference-data/notice-policy-storage/notice-policies/alternate-notice-policy.json, reference-data/notice-policy-storage/notice-policies/basic-notice-policy.json, reference-data/request-policy-storage/request-policies/allow-all.json, reference-data/request-policy-storage/request-policies/hold-only.json
Updated import script to include new data.
=> Created basic request and notice policies

descriptors/ModuleDescriptor-template.json, ramls/patron-notice-policy.json, ramls/patron-notice-policy.raml
=> CIRCSTORE-112 Backend: User initiated and time driven events for request related notices within notice policy

src/main/resources/templates/db_scripts/schema.json
Added a few indexes so loan related queries can be improved significantly (100x).
=> CIRCSTORE-115: Improve loan related query performance

pom.xml, src/main/java/org/folio/rest/impl/TenantRefAPI.java
The existing import.sh didn't do it correctly - but I guess
that's not to be used anymore.
=> Load patron-notice-policy-storage/patron-notice-policies

src/main/java/org/folio/rest/impl/TenantRefAPI.java
=> Fix path to sample loans and load path for loadSample tenant param.

src/main/java/org/folio/support/ExpirationTool.java
Resolves: CIRCSTORE-126
Not allow user to delete patron notice policy if currently in use
https://issues.folio.org/browse/CIRCSTORE-126
=> [CIRCSTORE-126] Implement database transactions in the request expiration process

descriptors/ModuleDescriptor-template.json, ramls/loan-storage.raml, ramls/loan.json
Loan schema was updated for storing patronGroupIdAtCheckout
=> CIRCSTORE-135: Store patron group in a loan at checkout.

descriptors/ModuleDescriptor-template.json, ramls/scheduled-notice-storage.raml, ramls/scheduled-notice.json
Add userId property to scheduled notice schema
Resolves: [CIRCSTORE-146](https://issues.folio.org/browse/CIRCSTORE-146)
=> [CIRCSTORE-146] Add userId property to scheduled notice schema

descriptors/ModuleDescriptor-template.json, ramls/examples/request-preference.json, ramls/examples/request-preferences.json, ramls/request-preference-storage.raml, ramls/request-preference.json, ramls/request-preferences.json, src/main/java/org/folio/rest/impl/RequestPreferencesAPI.java, src/main/java/org/folio/rest/impl/RequestPreferencesImpl.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/RequestPreferencesApiTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
Store user request preferences in mod-circulation-storage
Add CRUD endpoints and implement them by using PgUtil class
=> CIRC-436: Implementation for request-preference-storage

ramls/examples/loan.json, ramls/loan-storage.raml, ramls/loan.json, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
Needed for https://github.com/folio-org/mod-circulation/pull/339
=> CIRCSTORE-157: add itemEffectiveLocationAtCheckOut to loan

reference-data/circulation-rules-storage/single-rule.json
New default overdue fine policies added to the 'single-rule.json' file.
=> CIRCSTORE-160: Create default overdue fines policy.

reference-data/staff-slips-storage/staff-slips/pickSlip.json, src/test/java/org/folio/rest/api/StaffSlipsApiTest.java
**Purpose**
CIRCSTORE-504 View/edit/preview pick slip (aka call or page request slip)
**Approach**
added new pick slip entry with name "Pick slip" as a separate file.
=> CIRC-504 View/edit/preview pick slip (aka call or page request slip)

ramls/request.json, src/test/java/org/folio/rest/api/RequestsApiTest.java, src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
Add "Open - Awaiting delivery" status to support Fulfillment Delivery requests
Update request.json with the new status, make respective changes in the tests
=> CIRCSTORE-169  Add "Open - Awaiting delivery" status to Requests

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/examples/loan-policy.json, ramls/loan-policy-storage.raml, ramls/loan-policy.json, src/test/java/org/folio/rest/api/LoanPoliciesApiTest.java
**Purpose**
Add a new field to `Loan Policy`.
**Link**
[CIRCSTORE-170](https://issues.folio.org/browse/CIRCSTORE-170)
=> [CIRCSTORE-170] Add Item Limit to Loan Policy

src/main/java/org/folio/support/ExpirationTool.java, src/test/java/org/folio/rest/api/RequestExpirationApiTest.java
Update Expiration Tool to support expiration of delivery request
Resolves: [CIRC-509](https://issues.folio.org/browse/CIRC-509)
=> CIRC-509 Expiration of Delivery Requests

descriptors/ModuleDescriptor-template.json, ramls/loan-storage.raml, ramls/loan.json, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
Add new property for storing the date the item was declared lost
This resolves: CIRCSTORE-175
=> Circstore 175

descriptors/ModuleDescriptor-template.json, ramls/examples/loan.json, ramls/loan-storage.raml, ramls/loan.json, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
**Purpose**
Add effective Overdue Fine Policy and Lost Item Policy to loan schema
**Link**
[CIRCSTORE-177](https://issues.folio.org/browse/CIRCSTORE-177)
=> CIRCSTORE-177 Add effective Overdue Fine Policy and Lost Item Policy to loan schema

descriptors/ModuleDescriptor-template.json, ramls/loan-storage.raml, ramls/loan.json, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
https://issues.folio.org/browse/CIRCSTORE-187: Backend: Claim returned: mark an item claim returned
Add claimed returned date for loan.
=> CIRCSTORE-187: Add claimedReturnedDate property for loan.

reference-data/circulation-rules-storage/single-rule.json
https://issues.folio.org/browse/CIRCSTORE-192: Update lost-item and overdue fee policies in circulation rules
Related to https://github.com/folio-org/mod-feesfines/pull/68
=> CIRCSTORE-192: Set overdue and lost-item policies to circulation rules.

src/main/resources/templates/db_scripts/add_staff_slips.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/api/migration/MigrationTestBase.java, src/test/java/org/folio/rest/api/migration/StaffSlipsMigrationScriptTest.java
https://issues.folio.org/browse/CIRCSTORE-200
**Approach:**
- Create migration script for adding "Request delivery" staff slip
- Create migration script for adding "Pick slip" staff slip
=> CIRCSTORE-200 Create migration scripts for Q4 staff slips: Request delivery and Pick slips

descriptors/ModuleDescriptor-template.json, ramls/loan-storage.raml, ramls/loan.json, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
https://issues.folio.org/browse/CIRCSTORE-201 Claimed returned: mark an item missing
**Approach:** 
Add marked missing date for loan.
=> CIRCSTORE-201 Add markedMissingDate property to a loan

descriptors/ModuleDescriptor-template.json, ramls/interval.json, ramls/patron-notice-policy.json, ramls/patron-notice-policy.raml, ramls/scheduled-notice-storage.raml, ramls/scheduled-notice.json, src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java, src/test/java/org/folio/rest/api/ScheduledNoticesAPITest.java
To support implementation of [CIRC-711](https://issues.folio.org/browse/CIRC-711).
Resolves: [CIRCSTORE-207](https://issues.folio.org/browse/CIRCSTORE-207)
Original UI story: [UICIRC-451](https://issues.folio.org/browse/UICIRC-451)
=> [CIRCSTORE-207] Update schemas to support fee/fine scheduled notices

pom.xml, src/main/java/org/folio/rest/impl/AnonymizeStorageLoansAPI.java, src/main/java/org/folio/rest/impl/LoansAPI.java, src/main/java/org/folio/rest/impl/PatronActionSessionAPI.java, src/main/java/org/folio/rest/impl/PatronNoticePoliciesAPI.java, src/main/java/org/folio/rest/impl/RequestsAPI.java, src/main/java/org/folio/rest/impl/ScheduledNoticesAPI.java, src/main/java/org/folio/service/BatchResourceService.java, src/main/java/org/folio/service/request/RequestBatchResourceService.java, src/main/java/org/folio/support/DbUtil.java, src/main/java/org/folio/support/ExpirationTool.java, src/main/java/org/folio/support/PgClientFutureAdapter.java, src/main/java/org/folio/support/ResultHandlerFactory.java, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/api/PatronActionSessionAPITest.java, src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java, src/test/java/org/folio/rest/api/RequestBatchAPITest.java, src/test/java/org/folio/rest/api/RequestExpirationApiTest.java, src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java, src/test/java/org/folio/rest/api/RequestUpdateTriggerTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/support/ResultHandlerFactoryTest.java
https://issues.folio.org/browse/CIRCSTORE-212 - Upgrade to RAML Module Builder 30.0.0
=> CIRCSTORE-212: Upgrade to RMB v30

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
https://issues.folio.org/browse/CIRCSTORE-223 - Create b-tree index for loan status.name
=> CIRCSTORE-223: Add loan.status.name b-tree index.

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
https://issues.folio.org/browse/CIRCSTORE-230 - Add b-tree index for loan.itemStatus
=> CIRCSTORE-230: Add loan.itemStatus b-tree index.

NEWS.md, pom.xml
Upgrade RMB from 30.2.4 to 30.2.6. For details see NEWS.md.
=> CIRCSTORE-233: Release 12.0.3

descriptors/ModuleDescriptor-template.json, ramls/loan-storage.raml, ramls/loan.json, src/test/java/org/folio/rest/api/LoansApiTest.java, src/test/java/org/folio/rest/support/builders/LoanRequestBuilder.java
https://issues.folio.org/browse/CIRCSTORE-231 - Add loan.agedToLostDate property
* Add `agedToLostDate` property for loan;
* Bump `loan-storage` API version to `7.1`;
=> CIRCSTORE-231: Add loan.agedToLostDate property.

descriptors/ModuleDescriptor-template.json
[CIRCSTORE-247](https://issues.folio.org/browse/CIRCSTORE-247) - Request log actions: Pickup expired, Expired
=> CIRCSTORE-247 - Request log actions: Pickup expired, Expired

descriptors/ModuleDescriptor-template.json, ramls/request-storage.raml, ramls/request.json, src/test/java/org/folio/rest/api/RequestsApiTest.java, src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
Provide the storage for a String representing the Patron Comments.
Resolves: https://issues.folio.org/browse/CIRCSTORE-255
Update the loan-policy raml and its respective version.
Update the relevant tests, adding a new test.
Using `patronComments` to be consistent with provided mockups.
=> CIRCSTORE-255: Patron note on Request

descriptors/ModuleDescriptor-template.json, ramls/loan-policy-storage.raml, ramls/loan-policy.json, src/test/java/org/folio/rest/api/LoanPoliciesApiTest.java, src/test/java/org/folio/rest/support/builders/LoanPolicyRequestBuilder.java
Add the property to loan-policy. 
Bump `loan-policy-storage` API version to `2.3`.
Use lombok for `LoanPolicyRequestBuilder`.
=> CIRCSTORE-257: Add allowRecallsExtendOverdueLoans property to loan policy.

ramls/scheduled-notice.json, src/test/java/org/folio/rest/api/ScheduledNoticesAPITest.java
Resolves [CIRCSTORE-264](https://issues.folio.org/browse/CIRCSTORE-264)
=> [CIRCSTORE-264] Add new triggering events to Scheduled Notice schema

src/main/java/org/folio/rest/impl/PatronNoticePoliciesAPI.java, src/test/java/org/folio/rest/api/PatronNoticePoliciesApiTest.java
Fix validation for PUT-endpoint to allow editing of Patron Notice Policies which contain loan notices with triggering event "Aged to lost".
Resolves [CIRCSTORE-268](https://issues.folio.org/browse/CIRCSTORE-268).
=> [CIRCSTORE-268] Allow editing of notice policies with "Aged to lost" notices

src/main/java/org/folio/rest/impl/TenantRefAPI.java
[CIRCSTORE-265](https://issues.folio.org/browse/CIRCSTORE-265) - Pickup expired not showing in Circulation log
* Restored Pubsub registration
=> CIRCSTORE-265 - Pickup expired not showing in Circulation log

src/main/java/org/folio/service/PubSubRegistrationService.java
[CIRCSTORE-259](https://issues.folio.org/browse/CIRCSTORE-259) - PubSubRegistrationService code coverage improvement
Resulting PubSubRegistrationService coverage:
=> CIRCSTORE-259 - PubSubRegistrationService code coverage improvement

src/main/java/org/folio/rest/impl/AnonymizeStorageLoansAPI.java, src/main/java/org/folio/rest/impl/CancellationReasonsAPI.java, src/main/java/org/folio/rest/impl/CirculationRulesAPI.java, src/main/java/org/folio/rest/impl/FixedDueDateSchedulesAPI.java, src/main/java/org/folio/rest/impl/LoansAPI.java, src/main/java/org/folio/rest/impl/PatronActionSessionAPI.java, src/main/java/org/folio/rest/impl/PatronNoticePoliciesAPI.java, src/main/java/org/folio/rest/impl/RequestExpiryImpl.java, src/main/java/org/folio/rest/impl/RequestPoliciesAPI.java, src/main/java/org/folio/rest/impl/RequestPreferencesAPI.java, src/main/java/org/folio/rest/impl/RequestsAPI.java, src/main/java/org/folio/rest/impl/RequestsBatchAPI.java, src/main/java/org/folio/rest/impl/ScheduledNoticesAPI.java, src/main/java/org/folio/rest/impl/StaffSlipsAPI.java
Otherwise RMB doesn't validate the input against the API spec.
=> CIRCSTORE-287: Add @Validate to all API implementations

ramls/request.json, src/main/java/org/folio/service/tlr/TlrDataMigrationService.java, src/test/java/org/folio/rest/api/TenantRefApiTests.java
[CIRCSTORE-309](https://issues.folio.org/browse/CIRCSTORE-309)
_TLR data migration - add holdingsRecordId_
=> CIRCSTORE-309 implemented

pom.xml
[CIRCSTORE-312](https://issues.folio.org/browse/CIRCSTORE-312)
Upgrading to RMB v33.1.3 and Log4j v2.16.0
=> CIRCSTORE-312 Upgrade to RMB 33.1.3

descriptors/ModuleDescriptor-template.json
[CIRCSTORE-320](https://issues.folio.org/browse/CIRCSTORE-320)
_Add a dependency on mod-inventory-storage interface(s)_
=> CIRCSTORE-320: Add a dependency on mod-inventory-storage interface(s)

pom.xml, src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
Resolves: https://issues.folio.org/browse/CIRCSTORE-318
=> CIRCSTORE-318 Update RMB version to 33.2.4

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/CIRCSTORE-335
=> CIRCSTORE-335 Add index for loan.agedToLostDelayedBilling.dateLostItemShouldBeBilled field

ramls/kv-configuration.json, ramls/kv-configurations.json, ramls/tlr-feature-toggle-job.raml, src/main/java/org/folio/rest/client/ConfigurationClient.java, src/main/java/org/folio/service/tlr/TlrFeatureToggleService.java, src/test/java/org/folio/rest/api/TlrFeatureToggleJobAPITest.java
- add error handling for processing TLR toggle job;
- create tests;
Resolves: [CIRCSTORE-341](https://issues.folio.org/browse/CIRCSTORE-341)
=> CIRCSTORE-341 add error handling, add tests

src/main/java/org/folio/service/tlr/TlrDataMigrationService.java, src/test/java/org/folio/rest/api/TenantRefApiTests.java
https://issues.folio.org/browse/CIRCSTORE-340
=> [CIRCSTORE-340] Use default UUID for missing instanceId and holdingsRecordId

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/Headers.java, src/main/java/org/folio/rest/impl/RequestExpiryImpl.java, src/main/java/org/folio/service/EventPublisherService.java, src/main/java/org/folio/support/ExpirationTool.java, src/test/java/org/folio/rest/api/RequestExpirationApiTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/support/ApiTests.java
Resolves: https://issues.folio.org/browse/CIRCSTORE-342
=> Bugfix release 14.0.2

src/main/java/org/folio/support/ExpirationTool.java, src/test/java/org/folio/rest/api/RequestExpirationApiTest.java
https://issues.folio.org/browse/CIRCSTORE-350
=> CIRCSTORE-350: Update metadata.updatedDate upon request expiration

ramls/actual-cost-record.json, ramls/examples/actual-cost-record.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/ActualCostRecordAPITest.java
[CIRCSTORE-358](https://issues.folio.org/browse/CIRCSTORE-358)
=> CIRCSTORE-358: Update actualCostRecord schema

descriptors/ModuleDescriptor-template.json, ramls/actual-cost-record-storage.raml
Resolves [CIRCSTORE-364](https://issues.folio.org/browse/CIRCSTORE-364)
=> CIRCSTORE-364 Increment actual cost interface version

ramls/actual-cost-record.json, src/test/java/org/folio/rest/api/ActualCostRecordAPITest.java
https://issues.folio.org/browse/CIRCSTORE-370
=> CIRCSTORE-370: Add default status to Actual Cost Record

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/CIRCSTORE-375
=> CIRCSTORE-375 : Nolana bugfest missing index that is present in clean Nolana deployment

descriptors/ModuleDescriptor-template.json, ramls/actual-cost-record-storage.raml, ramls/actual-cost-record.json, ramls/examples/actual-cost-record.json, ramls/examples/actual-cost-records.json, src/test/java/org/folio/rest/api/ActualCostRecordAPITest.java
https://issues.folio.org/browse/CIRCSTORE-380
=> CIRCSTORE-380 Add contributors and effective location to Actual Cost Record

descriptors/ModuleDescriptor-template.json, ramls/actual-cost-record-storage.raml, ramls/actual-cost-record.json, ramls/examples/actual-cost-record.json, ramls/examples/actual-cost-records.json, src/test/java/org/folio/rest/api/ActualCostRecordAPITest.java
https://issues.folio.org/browse/CIRCSTORE-385
=> CIRCSTORE-385: Add billed amount to Actual Cost Record schema

descriptors/ModuleDescriptor-template.json, ramls/request-storage-batch.raml, ramls/request-storage.raml, ramls/request.json, src/test/java/org/folio/rest/api/RequestsApiTest.java
https://issues.folio.org/browse/CIRCSTORE-353
=> CIRCSTORE-353: Make request status required

pom.xml
Upgrade to folio-kafka-wrapper 2.7.0
Resolves [CIRCSTORE-396](https://issues.folio.org/browse/CIRCSTORE-396)
=> CIRCSTORE-396 Upgrade to folio-kafka-wrapper 2.7.0

NEWS.md, pom.xml
https://issues.folio.org/browse/CIRCSTORE-395
=> CIRCSTORE-395: Release mod-circluation-storage 16.0.0

src/main/resources/templates/db_scripts/schema.json
Resolves: [CIRCSTORE-397](https://issues.folio.org/browse/CIRCSTORE-397) Create index for Actual Cost Record status field
=> CIRCSTORE-397: Create index for Actual Cost Record 'status' field

src/main/java/org/folio/service/migration/AbstractRequestMigrationService.java, src/main/java/org/folio/service/migration/RequestSearchFieldsMigrationService.java, src/main/java/org/folio/service/migration/TlrDataMigrationService.java
Resolves [CIRCSTORE-400](https://issues.folio.org/browse/CIRCSTORE-400)
AbstractRequestMigrationService has two implementations and it's not clear in the logs which one is which
Add migrationName field to AbstractRequestMigrationService
Examples of logs:
```
17:45:15 [194415/proxy;510077/tenant] [fs09000000] [] [mod_circulation_storage] INFO uestMigrationService shouldMigrate:: all attributes for TLR migration are present: moduleFrom=mod-circulation-storage-16.1.0-SNAPSHOT.be4fb11, moduleTo=mod-circulation-storage-16.2.0-SNAPSHOT.d2c2856
--
Wed, Apr 26 2023 8:45:15 pm | 17:45:15 [194415/proxy;510077/tenant] [fs09000000] [] [mod_circulation_storage] INFO uestMigrationService shouldMigrate:: skipping TLR migration for module version 16.2.0-SNAPSHOT.d2c2856: previous version …
```
=> CIRCSTORE-400 Add logging to abstract request migration service

Dockerfile, Jenkinsfile, pom.xml
Migrate module from Java 11 to Java 17. 
Resolves: [CIRCSTORE-430](https://issues.folio.org/browse/CIRCSTORE-430) 
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
=> [CIRCSTORE-430] Migrate to Java 17

ramls/allowed-service-point-ids.json, ramls/examples/request-policy.json, ramls/request-policy.json, src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
Resolves [CIRCSTORE-424](https://issues.folio.org/browse/CIRCSTORE-424)
=> CIRCSTORE-424 Add allowed pickup service points to request policy schema

ramls/anonymize-storage-loans-response.json, ramls/cancellation-reason.json, ramls/fixed-due-date-schedule.json, ramls/kv-configuration.json, ramls/kv-configurations.json, ramls/loan-policy.json, ramls/patron-notice-policy.json, ramls/period.json, ramls/scheduled-notice.json, ramls/staff-slip.json, src/test/java/org/folio/rest/api/RequestPoliciesApiTest.java
Resolves [CIRCSTORE-409](https://issues.folio.org/browse/CIRCSTORE-409)
=> CIRCSTORE-409: Add missing descriptions to JSON-schemas

pom.xml
Resolves: [CIRCSTORE-459](https://issues.folio.org/browse/CIRCSTORE-459)
=> [CIRCSTORE-459] Update RMB to v35.1, Vert.x to v4.4.5

src/main/java/org/folio/persist/CirculationRulesRepository.java, src/main/java/org/folio/rest/impl/CirculationRulesAPI.java, src/main/java/org/folio/service/CirculationRulesService.java, src/main/java/org/folio/service/event/EntityChangedEventPublisher.java, src/main/java/org/folio/service/event/EntityChangedEventPublisherFactory.java, src/main/java/org/folio/support/kafka/topic/CirculationStorageKafkaTopic.java, src/test/java/org/folio/rest/api/CirculationRulesApiTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java, src/test/java/org/folio/service/kafka/topic/KafkaAdminClientServiceTest.java
[CIRCSTORE-470](https://issues.folio.org/browse/CIRCSTORE-470)
=> CIRCSTORE-470: Publish circulation rules update events

NEWS.md, pom.xml, src/main/java/org/folio/persist/CirculationRulesRepository.java, src/main/java/org/folio/rest/impl/CirculationRulesAPI.java, src/main/java/org/folio/service/CirculationRulesService.java, src/main/java/org/folio/service/event/EntityChangedEventPublisher.java, src/main/java/org/folio/service/event/EntityChangedEventPublisherFactory.java, src/main/java/org/folio/support/kafka/topic/CirculationStorageKafkaTopic.java, src/test/java/org/folio/rest/api/CirculationRulesApiTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java, src/test/java/org/folio/service/kafka/topic/KafkaAdminClientServiceTest.java
[CIRCSTORE-471](https://issues.folio.org/browse/CIRCSTORE-471)
Includes [CIRCSTORE-470](https://issues.folio.org/browse/CIRCSTORE-470) (#438)
=> Bugfix release 17.1.3

NEWS.md, pom.xml, src/main/resources/templates/db_scripts/schema.json
Resolves [CIRCSTORE-475](https://issues.folio.org/browse/CIRCSTORE-475)
Includes [CIRCSTORE-474](https://issues.folio.org/browse/CIRCSTORE-474) (#441)
=> CIRCSTORE-475: Release 17.1.4 (Poppy Bugfix)

pom.xml, src/main/java/org/folio/service/event/DomainEventPublisher.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
Resolves: [CIRCSTORE-473](https://issues.folio.org/browse/CIRCSTORE-473)
=> [CIRCSTORE-473] Update kafka-wrapper version

src/main/java/org/folio/service/event/DomainEventPublisher.java
Resolves: [CIRCSTORE-477](https://issues.folio.org/browse/CIRCSTORE-477)
=> [CIRCSTORE-477] Do not close Kafka producer after publishing

src/main/java/org/folio/service/event/DomainEventPublisher.java, src/main/java/org/folio/service/loan/LoanService.java
https://issues.folio.org/browse/CIRCSTORE-480
Adding more logging to confirm Kafka publishing issue on Poppy BugFest
=> CIRSTORE-480 - Add more logging to loan POST API

descriptors/ModuleDescriptor-template.json, ramls/actual-cost-record.json, ramls/examples/actual-cost-record.json, ramls/examples/actual-cost-records.json, src/test/java/org/folio/rest/api/ActualCostRecordAPITest.java
Resolves: [CIRCSTORE-493](https://folio-org.atlassian.net/browse/CIRCSTORE-493)
=> [CIRCSTORE-493] Add 'displaySummary' field to 'ActualCostRecord' schema

NEWS.md, pom.xml
Resolves: [CIRCSTORE-497](https://folio-org.atlassian.net/browse/CIRCSTORE-497)
=> [CIRCSTORE-497] Release 17.2.0

NEWS.md, pom.xml
Resolves: [CIRCSTORE-501](https://folio-org.atlassian.net/browse/CIRCSTORE-501)
=> [CIRCSTORE-501] Release 17.1.8

descriptors/ModuleDescriptor-template.json, ramls/request.json, src/test/java/org/folio/rest/api/RequestsApiTest.java, src/test/java/org/folio/rest/support/builders/RequestRequestBuilder.java
Resolves: [CIRCSTORE-502](https://folio-org.atlassian.net/browse/CIRCSTORE-502)
=> [CIRCSTORE-502] Add ecsRequestPhase field to request schema

descriptors/ModuleDescriptor-template.json
[CIRCSTORE-510](https://folio-org.atlassian.net/browse/CIRCSTORE-510)
=> CIRCSTORE-510: Update interface holdings-storage to version 7.0

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/test/java/org/folio/rest/api/TenantRefApiTests.java
[MODCIRC-518](https://folio-org.atlassian.net/browse/CIRCSTORE-518)
=> CIRCSTORE-518 Release mod-circulation-storage Q CSP#2

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/test/java/org/folio/rest/api/TenantRefApiTests.java
Reverts folio-org/mod-circulation-storage#472
=> Revert "CIRCSTORE-518 Release mod-circulation-storage Q CSP#2"

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/test/java/org/folio/rest/api/TenantRefApiTests.java
Resolves: [CIRCSTORE-518](https://folio-org.atlassian.net/browse/CIRCSTORE-518)
=> Release mod-circulation-storage Q CSP#2

src/main/java/org/folio/persist/AbstractRepository.java, src/main/java/org/folio/rest/impl/CirculationSettingsAPI.java, src/main/java/org/folio/service/CirculationSettingsService.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/CirculationSettingsAPITest.java
Purpose:
The purpose of the PR is to [CIRCSTORE-519](https://folio-org.atlassian.net/browse/CIRCSTORE-519)
Approach:
Change logic from save to update circulation settings with the same name value.
=> CIRCSTORE- 519 Update instead save with the same name circ settings.

NEWS.md, pom.xml
Resolves [CIRCSTORE-522](https://folio-org.atlassian.net/browse/CIRCSTORE-522)
=> [CIRCSTORE-522] Release v17.2.4 

NEWS.md, pom.xml
- Resolves [CIRCSTORE-523](https://folio-org.atlassian.net/browse/CIRCSTORE-523)
=> [CIRCSOTRE-523] Release v17.1.9

src/main/resources/templates/db_scripts/add_staff_slips_transit_mediated_requests.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/StaffSlipsApiTest.java, src/test/java/org/folio/rest/api/migration/StaffSlipsMigrationTestBase.java, src/test/java/org/folio/rest/api/migration/StaffSlipsTransitMediatedRequestsMigrationScriptTest.java
Purpose:
The purpose of the PR is to [CIRCSTORE-525](https://folio-org.atlassian.net/browse/CIRCSTORE-525)
Approach:
Create new transit staff slip for mediated request activities.
=> CIRCSTORE-525 Create new transit staff slip for mediated request activities

src/main/resources/templates/db_scripts/add_due_date_slips.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/StaffSlipsApiTest.java, src/test/java/org/folio/rest/api/migration/DueDateSlipsMigrationScriptTest.java
Purpose - https://folio-org.atlassian.net/browse/CIRCSTORE-529
=> CIRCSTORE-529 Persisting due date slip template.

NEWS.md, pom.xml
Purpose:
[CIRCSTORE-534](https://folio-org.atlassian.net/browse/CIRCSTORE-534)
=> CIRCSTORE-534: Release 17.3.0

descriptors/ModuleDescriptor-template.json
Resolves: [CIRCSTORE-524](https://folio-org.atlassian.net/browse/CIRCSTORE-524)
=> CIRCSTORE-524 Review and cleanup Module Descriptor for mod-circulation-storage

src/main/resources/templates/db_scripts/createIsbnFunctions.sql
https://folio-org.atlassian.net/browse/CIRCSTORE-553
Fix Postgres upgrade issue
Use full schema path in normalize_isbns  definition
=> CIRCSTORE-553: Create script to update normalize_isbns  to have full schema path

src/main/java/org/folio/EventConsumerVerticle.java, src/main/java/org/folio/service/event/InventoryEventType.java, src/main/java/org/folio/service/event/handler/LocationUpdateEventHandler.java, src/main/java/org/folio/service/event/handler/processor/ItemLocationUpdateProcessorForRequest.java, src/main/java/org/folio/support/kafka/topic/InventoryKafkaTopic.java, src/test/java/org/folio/rest/api/EventConsumerVerticleTest.java
https://folio-org.atlassian.net/browse/CIRCSTORE-556
=> CIRCSTORE-556: Add new LocationUpdateKafkaProcessor to sync location with request table

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/CIRCSTORE-575
=> Release v17.4.0

NEWS.md, descriptors/ModuleDescriptor-template.json, ramls/staff-slip.json
Bump interface `staff-slips-storage` to new minor version 1.1 to indictate the existence of this field.
=> [CIRCSTORE-585] New boolean `isRawHtml` in staff-slip JSON Schema

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/request-storage-batch.raml, ramls/settings-entries.json, ramls/settings-entry.json, ramls/settings-result-info.json, src/main/java/org/folio/rest/client/SettingsClient.java, src/main/java/org/folio/rest/configuration/TlrSettings.java, src/main/java/org/folio/service/request/RequestBatchResourceService.java, src/test/java/org/folio/rest/api/RequestBatchAPITest.java, src/test/java/org/folio/rest/api/RequestExpirationApiTest.java, src/test/java/org/folio/rest/api/TlrFeatureToggleJobAPITest.java, src/test/java/org/folio/rest/support/ApiTests.java
[CIRCSTORE-594](https://folio-org.atlassian.net/browse/CIRCSTORE-594)
=> CIRCSTORE-594: Release 17.3.6 (R2 2024 Ramsons CSP#3)

src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
Resolves: [CIRCSTORE-601](https://folio-org.atlassian.net/browse/CIRCSTORE-601)
=> CIRCSTORE-601 Fix timing issue in tests
